# Generated by Django 6.0.6 on 2026-09-08 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_complaints(apps, schema_editor):
    Complaint = apps.get_model("complaints", "Complaint")
    Notification = apps.get_model("companies", "CompanyNotification")
    alias = schema_editor.connection.alias
    batch = []
    timestamps = []
    for complaint in Complaint.objects.using(alias).all().iterator(chunk_size=500):
        batch.append(Notification(company_id=complaint.company_id, complaint_id=complaint.pk,
            kind="NEW", title="Şikayet kaydı çalışma alanına eklendi."))
        timestamps.append(complaint.created_at)
        if len(batch) == 500:
            Notification.objects.using(alias).bulk_create(batch)
            for notification, timestamp in zip(batch, timestamps):
                notification.created_at = timestamp
            Notification.objects.using(alias).bulk_update(batch, ["created_at"])
            batch, timestamps = [], []
    if batch:
        Notification.objects.using(alias).bulk_create(batch)
        for notification, timestamp in zip(batch, timestamps):
            notification.created_at = timestamp
        Notification.objects.using(alias).bulk_update(batch, ["created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_approval_status'),
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEW', 'Yeni şikayet'), ('PUBLISHED', 'Şikayet yayınlandı'), ('RESOLVED', 'Şikayet çözüldü'), ('UPDATED', 'Şikayet güncellendi'), ('ADMIN', 'Yönetim işlemi')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_notifications', to='companies.company')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='complaints.complaint')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CompanyNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='companies.companynotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='companies.company')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='complaints.complaint')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalCompanyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=3000)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='companies.company')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='complaints.complaint')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='companynotification',
            index=models.Index(fields=['company', '-created_at'], name='company_notification_recent'),
        ),
        migrations.AddConstraint(
            model_name='companynotificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_company_notification_read'),
        ),
        migrations.AddIndex(
            model_name='companyresponse',
            index=models.Index(fields=['company', 'is_active', '-created_at'], name='company_response_recent'),
        ),
        migrations.AddIndex(
            model_name='internalcompanynote',
            index=models.Index(fields=['company', 'complaint', '-created_at'], name='company_note_recent'),
        ),
        migrations.RunPython(seed_existing_complaints, migrations.RunPython.noop),
    ]
