# Generated by Django 6.0.6 on 2026-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_panel_communications'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
