# Generated by Django 6.0.6 on 2026-09-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynotification',
            name='event_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companynotification',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
