# Generated by Django 6.0.6 on 2026-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companynotification_event_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
