# Generated by Django 5.2.13 on 2026-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_seed_company_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynotification',
            name='kind',
            field=models.CharField(choices=[('NEW', 'Yeni şikayet'), ('PUBLISHED', 'Şikayet yayınlandı'), ('RESOLVED', 'Şikayet çözüldü'), ('REMOVED', 'Şikayet ihlal nedeniyle kaldırıldı'), ('UPDATED', 'Şikayet güncellendi'), ('ADMIN', 'Yönetim işlemi')], max_length=20),
        ),
    ]
