# Generated by Django 5.2.13 on 2026-09-13 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companynotification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('PRO', 'DertDerman Pro')], default='PRO', max_length=20)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Aylık'), ('YEARLY', 'Yıllık')], default='MONTHLY', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
