# Generated by Django 5.2.13 on 2026-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_rejected_at_company_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynotification',
            name='kind',
            field=models.CharField(choices=[('NEW', 'Yeni şikayet'), ('PUBLISHED', 'Şikayet yayınlandı'), ('RESOLVED', 'Şikayet çözüldü'), ('REMOVED', 'Şikayet ihlal nedeniyle kaldırıldı'), ('UPDATED', 'Şikayet güncellendi'), ('DERMAN', 'Yeni Derman'), ('ADMIN', 'Yönetim işlemi')], max_length=20),
        ),
    ]
