# Generated by Django 6.0.6 on 2026-09-24 12:27

from django.db import migrations, models


def clear_avatar_where_logo_exists(apps, schema_editor):
    company = apps.get_model('companies', 'Company')
    company.objects.using(schema_editor.connection.alias).exclude(
        models.Q(logo__isnull=True) | models.Q(logo='')
    ).exclude(selected_avatar='').update(selected_avatar='')


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companynotification_kind'),
    ]

    operations = [
        migrations.RunPython(clear_avatar_where_logo_exists, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('logo__isnull', True), ('logo', ''), ('selected_avatar', ''), _connector='OR'), name='company_one_visual_identity'),
        ),
    ]
