# Generated by Django 6.0.6 on 2026-09-09 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_companynotification_event_key_and_more'),
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('USER', 'Bireysel'), ('ADMIN', 'Yönetim')], max_length=10)),
                ('notification_type', models.CharField(choices=[('RECEIVED', 'Şikayet alındı'), ('PUBLISHED', 'Şikayet yayınlandı'), ('REJECTED', 'Şikayet reddedildi'), ('RESPONSE', 'Şirket yanıtı'), ('RESOLVED', 'Şikayet çözüldü'), ('UPDATED', 'Durum güncellemesi'), ('MODERATION', 'Moderasyon bekliyor'), ('APPLICATION', 'Şirket başvurusu')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('event_key', models.CharField(max_length=180)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_read', '-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient_user', 'recipient_role', 'is_read', '-created_at'], name='notification_inbox')],
                'constraints': [models.UniqueConstraint(fields=('recipient_user', 'recipient_role', 'event_key'), name='notification_recipient_event')],
            },
        ),
    ]
