# Generated by Django 6.0.6 on 2026-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RECEIVED', 'Şikayet alındı'), ('PUBLISHED', 'Şikayet yayınlandı'), ('REJECTED', 'Şikayet reddedildi'), ('RESPONSE', 'Şirket yanıtı'), ('RESOLVED', 'Şikayet çözüldü'), ('UPDATED', 'Durum güncellemesi'), ('MODERATION', 'Moderasyon bekliyor'), ('APPLICATION', 'Şirket başvurusu'), ('LIKE', 'Şikayet beğenisi'), ('REACTION', 'Şikayet tepkisi'), ('COMMENT', 'Şikayet yorumu')], max_length=20),
        ),
    ]
