# Generated by Django 5.2.13 on 2026-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iprisklog_abuseattempt'),
        ('notifications', '0003_notification_content_report_notification_user_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='abuse_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='core.abuseattempt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CREATED', 'Şikayet oluşturuldu'), ('PENDING', 'İncelemeye alındı'), ('PUBLISHED', 'Yayınlandı'), ('COMPANY_RESPONDED', 'Şirket cevapladı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı'), ('EDITED', 'Kullanıcı tarafından düzenlendi'), ('WITHDRAWN', 'Geri çekildi'), ('CONTENT_REPORT', 'İçerik raporu'), ('USER_REPORT', 'Kullanıcı raporu'), ('ABUSE_ALERT', 'Güvenlik olayı')], max_length=20),
        ),
    ]
