# Generated by Django 5.2.13 on 2026-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_abuse_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CREATED', 'Şikayet oluşturuldu'), ('PENDING', 'İncelemeye alındı'), ('PUBLISHED', 'Yayınlandı'), ('COMPANY_RESPONDED', 'Şirket cevapladı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı'), ('EDITED', 'Kullanıcı tarafından düzenlendi'), ('WITHDRAWN', 'Geri çekildi'), ('CONTENT_REPORT', 'İçerik raporu'), ('USER_REPORT', 'Kullanıcı raporu'), ('ABUSE_ALERT', 'Güvenlik olayı'), ('ACCOUNT_SUSPENDED', 'Hesap askıya alındı'), ('ACCOUNT_RESTORED', 'Hesap askısı kaldırıldı')], max_length=20),
        ),
    ]
