# Generated by Django 5.2.13 on 2026-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_companyreport_userviolation_company_report_and_more'),
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='complaints.companyreport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CREATED', 'Şikayet oluşturuldu'), ('PENDING', 'İncelemeye alındı'), ('PUBLISHED', 'Yayınlandı'), ('COMPANY_RESPONDED', 'Şirket cevapladı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı'), ('EDITED', 'Kullanıcı tarafından düzenlendi'), ('WITHDRAWN', 'Geri çekildi'), ('CONTENT_REPORT', 'İçerik raporu'), ('USER_REPORT', 'Kullanıcı raporu'), ('COMPANY_REPORT', 'Şirket raporu'), ('ABUSE_ALERT', 'Güvenlik olayı'), ('ACCOUNT_SUSPENDED', 'Hesap askıya alındı'), ('ACCOUNT_RESTORED', 'Hesap askısı kaldırıldı')], max_length=20),
        ),
    ]
