# Generated by Django 5.2.13 on 2026-09-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_company_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('recipient_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız'), ('SKIPPED', 'Atlandı')], default='PENDING', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_type', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='email_delivery_status')],
            },
        ),
    ]
