# Generated by Django 5.2.13 on 2026-09-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_email_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='provider_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Provider gönderdi'), ('DELIVERED', 'Teslim edildi'), ('DELAYED', 'Teslimat gecikti'), ('BOUNCED', 'Geri döndü'), ('COMPLAINED', 'Spam şikayeti'), ('FAILED', 'Provider başarısız'), ('SUPPRESSED', 'Provider tarafından bastırıldı')], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='provider_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='resend', max_length=32)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('processing_result', models.CharField(choices=[('MATCHED', 'Teslimatla eşleşti'), ('UNMATCHED', 'Teslimat bulunamadı'), ('IGNORED', 'Takip edilmeyen event')], db_index=True, default='IGNORED', max_length=16)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='notifications.emaildelivery')),
            ],
            options={
                'ordering': ('-received_at', '-pk'),
                'indexes': [models.Index(fields=['provider', 'provider_message_id', 'event_created_at'], name='email_webhook_lookup')],
            },
        ),
    ]
