# Generated by Django 5.2.13 on 2026-09-14 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_emaildelivery_provider_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PASSWORD_RESET', 'Şifre sıfırlama'), ('NOTIFICATION', 'Bildirim')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PROCESSING', 'İşleniyor'), ('RETRY', 'Yeniden denenecek'), ('SENT', 'Gönderildi'), ('DEAD', 'Kalıcı hata'), ('CANCELLED', 'İptal edildi')], default='PENDING', max_length=16)),
                ('recipient_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_state_hash', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(default='resend', max_length=32)),
                ('provider_idempotency_key', models.CharField(max_length=128, unique=True)),
                ('template_version', models.PositiveSmallIntegerField(default=1)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('provider_retry_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_outbox_item', to='notifications.notification')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_outbox_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='outbox',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='notifications.emailoutbox'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['status', 'available_at'], name='email_outbox_available'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['status', 'lease_expires_at'], name='email_outbox_lease'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['kind', 'status', 'created_at'], name='email_outbox_kind_status'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'NOTIFICATION'), ('notification__isnull', False), ('recipient_user__isnull', False), ('request_state_hash', ''), ('token_issued_at__isnull', True), models.Q(('recipient_hash', ''), _negated=True)), models.Q(('expires_at__isnull', False), ('kind', 'PASSWORD_RESET'), ('notification__isnull', True), ('recipient_user__isnull', False), ('token_issued_at__isnull', False), models.Q(('recipient_hash', ''), _negated=True), models.Q(('request_state_hash', ''), _negated=True)), models.Q(('expires_at__isnull', True), ('kind', 'PASSWORD_RESET'), ('notification__isnull', True), ('recipient_hash', ''), ('recipient_user__isnull', True), ('request_state_hash', ''), ('token_issued_at__isnull', True)), _connector='OR'), name='email_outbox_recipe'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_token__isnull', False), ('claimed_at__isnull', False), ('lease_expires_at__isnull', False), ('status', 'PROCESSING')), models.Q(models.Q(('status', 'PROCESSING'), _negated=True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('lease_expires_at__isnull', True)), _connector='OR'), name='email_outbox_claim_fields'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('SENT', 'DEAD', 'CANCELLED')), ('completed_at__isnull', False)), models.Q(models.Q(('status__in', ('SENT', 'DEAD', 'CANCELLED')), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='email_outbox_completed'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='email_outbox_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider', ''), _negated=True), models.Q(('provider_idempotency_key', ''), _negated=True)), name='email_outbox_provider_key'),
        ),
    ]
