# Generated by Django 5.2.13 on 2026-09-14 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_emailoutbox_emaildelivery_outbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailoutbox',
            name='email_outbox_recipe',
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='kind',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Şifre sıfırlama'), ('EMAIL_VERIFICATION', 'E-posta doğrulama'), ('NOTIFICATION', 'Bildirim')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'NOTIFICATION'), ('notification__isnull', False), ('recipient_user__isnull', False), ('request_state_hash', ''), ('token_issued_at__isnull', True), models.Q(('recipient_hash', ''), _negated=True)), models.Q(('expires_at__isnull', False), ('kind', 'PASSWORD_RESET'), ('notification__isnull', True), ('recipient_user__isnull', False), ('token_issued_at__isnull', False), models.Q(('recipient_hash', ''), _negated=True), models.Q(('request_state_hash', ''), _negated=True)), models.Q(('expires_at__isnull', False), ('kind', 'EMAIL_VERIFICATION'), ('notification__isnull', True), ('recipient_user__isnull', False), ('token_issued_at__isnull', False), models.Q(('recipient_hash', ''), _negated=True), models.Q(('request_state_hash', ''), _negated=True)), models.Q(('expires_at__isnull', True), ('kind', 'PASSWORD_RESET'), ('notification__isnull', True), ('recipient_hash', ''), ('recipient_user__isnull', True), ('request_state_hash', ''), ('token_issued_at__isnull', True)), _connector='OR'), name='email_outbox_recipe'),
        ),
    ]
