# Generated by Django 5.2.13 on 2026-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_emailoutbox_email_outbox_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='render_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
