# Generated by Django 5.2.13 on 2026-09-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_emailoutbox_render_failure_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emaildelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('provider', 'provider_message_id'), name='email_delivery_provider_msg_uq'),
        ),
    ]
