# Generated by Django 6.0.6 on 2026-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('GENERAL', 'Genel İletişim'), ('TECHNICAL', 'Teknik Destek'), ('COMPANY', 'Şirket / Marka Talebi'), ('COMPLAINT', 'Şikayetle İlgili Destek'), ('OTHER', 'Diğer')], max_length=20)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('NEW', 'Yeni'), ('READ', 'Okundu'), ('CLOSED', 'Kapalı')], db_index=True, default='NEW', max_length=12)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
