# Generated by Django 5.2.13 on 2026-09-11 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('SUSPICIOUS', 'Şüpheli'), ('BLOCKED', 'Engelli')], db_index=True, default='NORMAL', max_length=12)),
                ('account_count_24h', models.PositiveIntegerField(default=0)),
                ('spam_attempt_count', models.PositiveIntegerField(default=0)),
                ('rate_limit_count', models.PositiveIntegerField(default=0)),
                ('first_account_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_account_created_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
                'indexes': [models.Index(fields=['status', '-updated_at'], name='ip_risk_status')],
            },
        ),
        migrations.CreateModel(
            name='AbuseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('COMPLAINT_RATE_LIMIT_10M', '10 dakikalık şikayet limiti'), ('COMPLAINT_RATE_LIMIT_1H', '1 saatlik şikayet limiti'), ('COMPLAINT_RATE_LIMIT_24H', '24 saatlik şikayet limiti'), ('NEW_ACCOUNT_LIMIT', 'Yeni hesap şikayet limiti'), ('UNVERIFIED_ACCOUNT', 'Doğrulanmamış hesap'), ('SAME_COMPANY_COOLDOWN', 'Aynı şirkete cooldown'), ('DUPLICATE_COMPLAINT', 'Aynı şikayeti tekrar gönderme'), ('SIMILAR_COMPLAINT', 'Benzer şikayet gönderme'), ('FORM_TOO_FAST', 'Form olağandışı hızlı gönderildi'), ('OPEN_COMPLAINT_LIMIT', 'Açık şikayet limiti'), ('REJECTION_RESTRICTION', 'Reddedilme geçmişi kısıtı'), ('ACCOUNT_CREATION_LIMIT', 'IP hesap oluşturma limiti'), ('IP_ABUSE_BLOCK', 'IP kötüye kullanım engeli'), ('OTHER', 'Diğer')], db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='abuse_user_recent'), models.Index(fields=['ip_address', '-created_at'], name='abuse_ip_recent'), models.Index(fields=['event_type', '-created_at'], name='abuse_event_recent')],
            },
        ),
    ]
