# Generated by Django 5.2.13 on 2026-09-06 13:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('excerpt', models.CharField(max_length=320, verbose_name='Kısa açıklama')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, upload_to=blog.models.cover_upload_path, verbose_name='Kapak görseli')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PUBLISHED', 'Yayında')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_publication_idx')],
            },
        ),
    ]
