# Generated by Django 6.0.6 on 2026-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('PUBLISHED', 'Yayında'), ('ARCHIVED', 'Silindi / Arşivlendi')], default='DRAFT', max_length=12),
        ),
    ]
