# Generated by Django 6.0.6 on 2026-09-09 17:30

from django.db import migrations, models


def convert_legacy_reactions(apps, schema_editor):
    Reaction = apps.get_model("complaints", "ComplaintReaction")
    mapping = {"AGREE": "👍", "SUPPORT": "❤️", "SURPRISED": "😮", "SAD": "😕"}
    for old, emoji in mapping.items():
        Reaction.objects.filter(reaction_type=old).update(reaction_type=emoji)


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaintcomment_complaintlike_complaintreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaintevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Şikayet oluşturuldu'), ('PENDING', 'İncelemeye alındı'), ('PUBLISHED', 'Yayınlandı'), ('COMPANY_RESPONDED', 'Şirket cevapladı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('EDITED', 'Kullanıcı tarafından düzenlendi'), ('WITHDRAWN', 'Geri çekildi')], max_length=24),
        ),
        migrations.AlterField(
            model_name='complaintreaction',
            name='reaction_type',
            field=models.CharField(max_length=32),
        ),
        migrations.RunPython(convert_legacy_reactions, migrations.RunPython.noop),
    ]
