# Generated by Django 5.2.13 on 2026-09-10 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_withdrawn_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('COMPLAINT', 'Şikayet'), ('COMMENT', 'Yorum')], max_length=20)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam / reklam'), ('HARASSMENT', 'Hakaret / taciz'), ('HATE', 'Nefret söylemi'), ('PERSONAL_DATA', 'Kişisel veri paylaşımı'), ('MISLEADING', 'Yanıltıcı içerik'), ('ILLEGAL', 'Yasa dışı içerik'), ('OTHER', 'Diğer')], max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'İncelenmeyi bekliyor'), ('REVIEWING', 'İnceleniyor'), ('RESOLVED', 'Sonuçlandırıldı'), ('REJECTED', 'İhlal bulunmadı')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='complaints.complaintcomment')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='complaints.complaint')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_report_status'), models.Index(fields=['target_type', '-created_at'], name='content_report_target'), models.Index(fields=['reporter', '-created_at'], name='content_report_reporter')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('complaint__isnull', False)), fields=('reporter', 'complaint'), name='unique_user_complaint_report'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_user_comment_report')],
            },
        ),
    ]
