# Generated by Django 5.2.13 on 2026-09-10 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_contentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='removed_for_violation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='violation_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='violation_removed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='violation_removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_removed_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='violation_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_complaints', to='complaints.contentreport'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'İncelemede'), ('PUBLISHED', 'Yayında'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı')], default='PENDING', max_length=20),
        ),
    ]
