# Generated by Django 5.2.13 on 2026-09-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_removed_for_violation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Şikayet oluşturuldu'), ('PENDING', 'İncelemeye alındı'), ('PUBLISHED', 'Yayınlandı'), ('COMPANY_RESPONDED', 'Şirket cevapladı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı'), ('EDITED', 'Kullanıcı tarafından düzenlendi'), ('WITHDRAWN', 'Geri çekildi')], max_length=24),
        ),
    ]
