# Generated by Django 5.2.13 on 2026-09-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_complaintevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam / reklam'), ('HARASSMENT', 'Hakaret / taciz'), ('FAKE_ACCOUNT', 'Sahte hesap'), ('THREAT', 'Tehdit'), ('PERSONAL_DATA', 'Kişisel veri ihlali'), ('ABUSE', 'Sistemi kötüye kullanma'), ('OTHER', 'Diğer')], max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'İncelenmeyi bekliyor'), ('REVIEWING', 'İnceleniyor'), ('RESOLVED', 'İhlal doğrulandı'), ('REJECTED', 'İhlal bulunmadı')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='UserViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('COMPLAINT', 'Şikayet'), ('COMMENT', 'Yorum'), ('USER_REPORT', 'Kullanıcı raporu')], max_length=20)),
                ('reason', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_violations', to='complaints.complaintcomment')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_violations', to='complaints.complaint')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_user_violations', to=settings.AUTH_USER_MODEL)),
                ('content_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_violations', to='complaints.contentreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='complaints.userreport')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', '-created_at'], name='user_report_status'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user', '-created_at'], name='user_report_target'),
        ),
        migrations.AddConstraint(
            model_name='userreport',
            constraint=models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='user_report_no_self_report'),
        ),
        migrations.AddConstraint(
            model_name='userreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'REVIEWING'))), fields=('reporter', 'reported_user'), name='unique_open_user_report'),
        ),
        migrations.AddIndex(
            model_name='userviolation',
            index=models.Index(fields=['user', '-created_at'], name='user_violation_history'),
        ),
        migrations.AddConstraint(
            model_name='userviolation',
            constraint=models.UniqueConstraint(condition=models.Q(('content_report__isnull', False)), fields=('content_report',), name='unique_content_report_violation'),
        ),
        migrations.AddConstraint(
            model_name='userviolation',
            constraint=models.UniqueConstraint(condition=models.Q(('user_report__isnull', False)), fields=('user_report',), name='unique_user_report_violation'),
        ),
    ]
