# Generated by Django 5.2.13 on 2026-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_userreport_userviolation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'İncelenmeyi bekliyor'), ('REVIEWING', 'İnceleniyor'), ('RESOLVED', 'İhlal bulundu'), ('REJECTED', 'İhlal bulunmadı'), ('ABUSIVE', 'Kötü niyetli / asılsız rapor')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userviolation',
            name='source_type',
            field=models.CharField(choices=[('COMPLAINT', 'Şikayet'), ('COMMENT', 'Yorum'), ('USER_REPORT', 'Kullanıcı raporu'), ('FALSE_REPORT', 'Kötü niyetli raporlama')], max_length=20),
        ),
    ]
