# Generated by Django 5.2.13 on 2026-09-11 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_contentreport_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userreport',
            name='unique_open_user_report',
        ),
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'İncelenmeyi bekliyor'), ('REVIEWING', 'İnceleniyor'), ('RESOLVED', 'İhlal doğrulandı'), ('REJECTED', 'İhlal bulunmadı'), ('ABUSIVE', 'Kötü niyetli / asılsız rapor')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'reported_user'), name='unique_user_report'),
        ),
    ]
