# Generated by Django 5.2.13 on 2026-09-11 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_remove_userreport_unique_open_user_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROBATION', 'Raporlama gözetimi'), ('FULL_BLOCK', 'Şikayet ve raporlama kısıtı')], db_index=True, max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_report_restrictions', to='complaints.userviolation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['user', 'kind', 'ends_at'], name='report_restriction_active')],
            },
        ),
    ]
