# Generated by Django 5.2.13 on 2026-09-11 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companynotification_kind'),
        ('complaints', '0011_reportrestriction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FRAUD', 'Dolandırıcılık / sahtecilik şüphesi'), ('MISLEADING', 'Yanıltıcı şirket bilgisi'), ('IMPERSONATION', 'Başka şirketi taklit etme'), ('ABUSE', 'Sistemi kötüye kullanma'), ('ILLEGAL', 'Yasa dışı faaliyet / içerik'), ('OTHER', 'Diğer')], max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'İncelenmeyi bekliyor'), ('REVIEWING', 'İnceleniyor'), ('RESOLVED', 'İhlal doğrulandı'), ('REJECTED', 'İhlal bulunmadı'), ('ABUSIVE', 'Kötü niyetli / asılsız rapor')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_company_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_company_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='userviolation',
            name='company_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='complaints.companyreport'),
        ),
        migrations.AddConstraint(
            model_name='userviolation',
            constraint=models.UniqueConstraint(condition=models.Q(('company_report__isnull', False)), fields=('company_report',), name='unique_company_report_violation'),
        ),
        migrations.AddIndex(
            model_name='companyreport',
            index=models.Index(fields=['status', '-created_at'], name='company_report_status'),
        ),
        migrations.AddIndex(
            model_name='companyreport',
            index=models.Index(fields=['company', '-created_at'], name='company_report_target'),
        ),
        migrations.AddConstraint(
            model_name='companyreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'company'), name='unique_user_company_report'),
        ),
    ]
