# Generated by Django 5.2.13 on 2026-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_companyreport_userviolation_company_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
