# Generated by Django 5.2.13 on 2026-09-12 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companynotification_kind'),
        ('complaints', '0013_complaint_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-created_at', '-pk')},
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('PRODUCT_SERVICE', 'Ürün / Hizmet Kalitesi'), ('DELIVERY', 'Teslimat / Kargo'), ('REFUND', 'İade / Ücret'), ('BILLING', 'Ödeme / Faturalandırma'), ('CUSTOMER_SERVICE', 'Müşteri Hizmetleri'), ('ACCOUNT', 'Hesap / Üyelik'), ('TECHNICAL', 'Teknik Sorun'), ('CAMPAIGN_PRICE', 'Kampanya / Fiyat'), ('WARRANTY_SERVICE', 'Garanti / Servis'), ('PRIVACY_SECURITY', 'Gizlilik / Güvenlik'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['company', 'category', 'status', '-created_at'], name='compl_pub_cat_recent'),
        ),
    ]
