# Generated by Django 5.2.13 on 2026-09-15 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaint_options_complaint_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('complaint__isnull', False), ('target_type', 'COMPLAINT')), models.Q(('comment__isnull', False), ('complaint__isnull', True), ('target_type', 'COMMENT')), _connector='OR'), name='content_report_target_ck'),
        ),
    ]
