# Generated by Django 5.2.13 on 2026-09-16 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_rejected_at_company_rejection_reason'),
        ('complaints', '0015_harden_content_report_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DermanCompanyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DermanPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'İnceleme bekliyor'), ('PUBLISHED', 'Yayında'), ('REJECTED', 'Reddedildi'), ('WITHDRAWN', 'Geri çekildi'), ('REMOVED', 'İhlal nedeniyle kaldırıldı')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True, default='', max_length=1000)),
                ('removed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('removal_reason', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DermanReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Beğendim'), ('DISLIKE', 'Beğenmedim')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='contentreport',
            name='content_report_target_ck',
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=[('COMPLAINT', 'Şikayet'), ('COMMENT', 'Yorum'), ('DERMAN', 'Derman Ol')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userviolation',
            name='source_type',
            field=models.CharField(choices=[('COMPLAINT', 'Şikayet'), ('COMMENT', 'Yorum'), ('DERMAN', 'Derman Ol'), ('USER_REPORT', 'Kullanıcı raporu'), ('FALSE_REPORT', 'Kötü niyetli raporlama')], max_length=20),
        ),
        migrations.AddField(
            model_name='dermancompanyresponse',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derman_company_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dermancompanyresponse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derman_responses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='dermanpost',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derman_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dermanpost',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derman_posts', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='dermanpost',
            name='removal_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_derman_posts', to='complaints.contentreport'),
        ),
        migrations.AddField(
            model_name='dermanpost',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_derman_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dermanpost',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_derman_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dermancompanyresponse',
            name='derman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_responses', to='complaints.dermanpost'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='derman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='complaints.dermanpost'),
        ),
        migrations.AddField(
            model_name='userviolation',
            name='derman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_violations', to='complaints.dermanpost'),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('complaint__isnull', False), ('derman__isnull', True), ('target_type', 'COMPLAINT')), models.Q(('comment__isnull', False), ('complaint__isnull', True), ('derman__isnull', True), ('target_type', 'COMMENT')), models.Q(('comment__isnull', True), ('complaint__isnull', True), ('derman__isnull', False), ('target_type', 'DERMAN')), _connector='OR'), name='content_report_target_ck'),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('derman__isnull', False)), fields=('reporter', 'derman'), name='unique_user_derman_report'),
        ),
        migrations.AddField(
            model_name='dermanreaction',
            name='derman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='complaints.dermanpost'),
        ),
        migrations.AddField(
            model_name='dermanreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derman_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dermanpost',
            index=models.Index(fields=['complaint', 'status', '-created_at'], name='derman_compl_status'),
        ),
        migrations.AddIndex(
            model_name='dermanpost',
            index=models.Index(fields=['status', '-created_at'], name='derman_mod_status'),
        ),
        migrations.AddConstraint(
            model_name='dermanpost',
            constraint=models.UniqueConstraint(fields=('complaint', 'author_user'), name='unique_derman_per_complaint_user'),
        ),
        migrations.AddConstraint(
            model_name='dermanpost',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'PUBLISHED', 'REJECTED', 'WITHDRAWN', 'REMOVED'))), name='derman_valid_status'),
        ),
        migrations.AddIndex(
            model_name='dermancompanyresponse',
            index=models.Index(fields=['company', 'derman'], name='derman_company_lookup'),
        ),
        migrations.AddConstraint(
            model_name='dermancompanyresponse',
            constraint=models.UniqueConstraint(fields=('derman', 'company'), name='unique_derman_company_response'),
        ),
        migrations.AddIndex(
            model_name='dermanreaction',
            index=models.Index(fields=['derman', 'reaction_type'], name='derman_reaction_count'),
        ),
        migrations.AddConstraint(
            model_name='dermanreaction',
            constraint=models.UniqueConstraint(fields=('derman', 'user'), name='unique_derman_reaction'),
        ),
        migrations.AddConstraint(
            model_name='dermanreaction',
            constraint=models.CheckConstraint(condition=models.Q(('reaction_type__in', ('LIKE', 'DISLIKE'))), name='derman_reaction_valid_type'),
        ),
    ]
