# Generated by Django 5.2.13 on 2026-09-10 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('PUBLISH', 'Yayınlama'), ('REJECT', 'Reddetme'), ('RESOLVE', 'Çözüldü olarak işaretleme'), ('ARCHIVE', 'Arşivleme'), ('RESTORE', 'Geri yükleme'), ('SUSPEND', 'Kısıtlama'), ('OTHER', 'Diğer')], max_length=20)),
                ('target_type', models.CharField(help_text='İşlem yapılan nesnenin türü. Örn: complaint, user, company.', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='İşlem yapılan nesnenin kimliği.', max_length=100)),
                ('target_label', models.CharField(blank=True, default='', help_text='İşlem yapılan nesnenin okunabilir adı.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['actor', '-created_at'], name='admin_audit_actor_time'), models.Index(fields=['target_type', 'target_id'], name='admin_audit_target'), models.Index(fields=['action', '-created_at'], name='admin_audit_action_time')],
            },
        ),
    ]
