# Generated by Django 6.0.6 on 2026-09-09 17:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
